export const swiggy="https://cdn.worldvectorlogo.com/logos/swiggy-1.svg"
export const home="https://cdn4.iconfinder.com/data/icons/essentials-72/24/046_-_House-64.png"
export const aboutUs="https://cdn4.iconfinder.com/data/icons/basic-ui-element-flat-style/512/Basic_UI_Elements_-_2.3_-_Flat_Style_-_36-39-64.png"
export const contact="https://cdn2.iconfinder.com/data/icons/people-flat-design/64/Support-Customer-Call_Center-Helpline-Contact-Service-Headset-64.png"
export const cart="https://cdn1.iconfinder.com/data/icons/shopping-e-commerce-10/33/cart_2-2-64.png"
export const Biryani="https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1675667625/PC_Creative%20refresh/Biryani_2.png"
export const swiggyApi= "https://www.swiggy.com/dapi/restaurants/list/v5?lat=12.9351929&lng=77.62448069999999&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING"
export const Cdn = "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/"
export const IMG = "v1675667625/PC_Creative%20refresh/Biryani_2.png"